"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export const languages = [
  { value: "nl", label: "Nederlands", shortLabel: "NL", flag: "🇧🇪", htmlLang: "nl-BE" },
  { value: "en", label: "English", shortLabel: "EN", flag: "🇬🇧", htmlLang: "en" },
  { value: "fr", label: "Français", shortLabel: "FR", flag: "🇫🇷", htmlLang: "fr" },
  { value: "de", label: "Deutsch", shortLabel: "DE", flag: "🇩🇪", htmlLang: "de" },
] as const;

export type Language = (typeof languages)[number]["value"];

const nl = {
  "nav.home": "Home", "nav.about": "Over Cannix", "nav.gallery": "Foto's", "nav.contact": "Contact",
  "nav.videos": "Video's", "nav.main": "Hoofdnavigatie", "nav.mobile": "Mobiele navigatie",
  "nav.open": "Menu openen", "nav.close": "Menu sluiten", "nav.language": "Taal kiezen",
  "header.home": "Cannix home", "booking": "Boek Cannix", "language.label": "Taal",
  "cookie.title": "Wij gebruiken cookies 🍪",
  "cookie.description": "Deze website gebruikt functionele cookies voor een optimale ervaring. Geen tracking of externe analytische diensten.",
  "cookie.more": "Lees meer", "cookie.accept": "Accepteren", "cookie.decline": "Weigeren", "close": "Sluiten",
  "splash.welcome": "Welkomscherm", "splash.continue": "Ga verder", "splash.continueLabel": "Ga verder naar de website",
  "notFound.title": "Pagina niet gevonden", "notFound.description": "De pagina die je zoekt bestaat niet of is verplaatst. Geen worries — de beat gaat door.", "notFound.home": "Terug naar Home",
  "home.nextGig": "Volgende gig", "home.description": "Belgische DJ gespecialiseerd in energieke festivalsets, fuifclassics, meezingers en harde remixes.",
  "home.nextEvent": "Volgend evenement", "home.tickets": "Tickets & Info", "home.about": "Over Cannix",
  "home.musicConnects": "Muziek die verbindt", "home.readMore": "Lees meer", "home.bookingsOpen": "Boekingen open",
  "home.availability": "Vraag beschikbaarheid aan", "home.contact": "Contact opnemen", "home.genres": "Genres",
  "home.follow": "Volg de vibe", "home.stats.age": "Leeftijd", "home.stats.experience": "Jaar ervaring",
  "home.stats.shows": "Optredens", "home.stats.festivals": "Festivals", "home.stats.countries": "Landen",
  "home.alt": "DJ Cannix live op PEMP 2024",
  "about.title": "Energie, Beats & Unieke Sfeer", "about.subtitle": "Passie voor het meeslepen van de dansvloer, van meezingers en fuifclassics tot harde DnB & hardstyle.",
  "about.musicStyle": "Mijn Muziek & Stijl", "about.style1": "Als allround DJ draai ik vooral herkenbare fuifmuziek, echte meezingers en hardere remixes. Daarnaast draai en produceer ik Drum & Bass, met een focus op onder andere Jump Up. Ook Hardstyle en Jumpstyle komen regelmatig terug in mijn sets.",
  "about.style2": "Ik ben altijd op zoek naar nieuwe muziek en nieuwe sounds. Wat ik draai hangt af van het publiek, de locatie en de sfeer van het moment. Het belangrijkste is dat mensen bewegen en betrokken blijven bij de muziek.",
  "about.figures": "Cijfers", "about.bookings": "Boekingen & Contact", "about.interest": "Interesse in een booking? Stuur gerust een bericht voor meer informatie en beschikbaarheid.",
  "about.drives": "Waar het om draait", "about.drivesText": "Muziek draaien gaat voor mij vooral om de sfeer en het publiek.",
  "about.energy": "Energie", "about.energyText": "Een goede set moet energie geven en ervoor zorgen dat de dansvloer blijft bewegen.",
  "about.music": "Muziek", "about.musicText": "Van bekende meezingers tot DnB en hardere remixes. Ik blijf graag nieuwe muziek ontdekken.",
  "about.audience": "Publiek", "about.audienceText": "Ik kijk naar de zaal en speel in op wat er op dat moment gebeurt. Het publiek bepaalt mee de richting.",
  "contact.title": "Contact & Samenwerking", "contact.heading": "Laten we samenwerken",
  "contact.intro": "Heb je een boekingsaanvraag, algemene vraag, samenwerkingsidee of media-aanvraag? Vul het formulier in en we nemen binnen 24u contact op.",
  "contact.send": "Stuur een bericht", "contact.direct": "Direct contact", "contact.bookings": "Contact & boekingen",
  "contact.phone": "Telefoon", "contact.location": "Locatie", "contact.locationValue": "België (Europees boekbaar)",
  "contact.whatNeed": "Wat we nodig hebben", "contact.needIntro": "Voor een passend voorstel helpen deze details:",
  "contact.date": "Datum & tijdstip", "contact.venue": "Locatie / venue", "contact.attendees": "Verwacht aantal bezoekers",
  "contact.vibe": "Muzikale richting / vibe", "contact.budget": "Budget indicatie", "contact.socials": "Socials",
  "contact.faq": "Veelgestelde vragen", "contact.faqIntro": "De meest voorkomende vragen over contact en boekingen.",
  "faq.1q": "Hoe ver van tevoren moet ik boeken?", "faq.1a": "Voor weekends en festivals raden we 2–3 maanden van tevoren aan. Weekdagen en last-minute zijn soms mogelijk, afhankelijk van de agenda.",
  "faq.2q": "Wat is de prijs van een set?", "faq.2a": "Prijzen variëren op basis van duur, locatie, dag van de week, uitrusting en of het een club/festival/private event is. Stuur een aanvraag voor een maatwerk offerte.",
  "faq.3q": "Breng je eigen apparatuur?", "faq.3a": "Standaard speel ik op de house gear (CDJ-3000 / mixer). Voor specifieke riders of eigen controller: overleg van tevoren.",
  "faq.4q": "Speel je ook op bruiloften / corporate events?", "faq.4a": "Absoluut. Ik heb ruime ervaring met private events en pas de muziek volledig aan aan de sfeer en gewensten van de organisator.",
  "faq.5q": "Hoe ver reis je?", "faq.5a": "Vanaf België Europees. Reis- en verblijfkosten komen niet bovenop de prijs voor optredens buiten Europa.",
  "faq.6q": "Kan ik een demo of live set horen?", "faq.6a": "Zeker. Luister naar mixes en producties op SoundCloud of vraag een live demo aan via het formulier.",
  "form.name": "Naam", "form.namePlaceholder": "Je naam", "form.email": "E-mail", "form.website": "Website", "form.reason": "Waarvoor neem je contact op?",
  "form.choose": "Maak een keuze", "form.phone": "Telefoon", "form.eventType": "Type evenement",
  "form.eventChoose": "Kies een type evenement", "form.questionSubject": "Onderwerp van je vraag",
  "form.collaborationType": "Type samenwerking", "form.mediaType": "Type media-aanvraag", "form.date": "Datum",
  "form.optional": "Optioneel", "form.location": "Locatie", "form.locationPlaceholder": "Stad / venue",
  "form.message": "Bericht", "form.messagePlaceholder": "Vertel kort over je event, timing, verwacht aantal bezoekers en wat je zoekt.",
  "form.send": "Verstuur aanvraag", "form.sending": "Versturen...", "form.error": "Versturen lukte niet.",
  "form.retry": "Probeer opnieuw of mail direct naar bookings@cannix.be.", "form.successTitle": "Aanvraag verstuurd",
  "form.thanks": "Bedankt voor je aanvraag.", "form.successText": "We nemen zo snel mogelijk contact met je op.",
  "form.event.club": "Clubavond", "form.event.festival": "Festival", "form.event.party": "Fuif", "form.event.rave": "Rave",
  "form.event.private": "Private party", "form.event.wedding": "Bruiloft", "form.event.other": "Anders",
  "form.reason.booking": "Ik wil Cannix boeken", "form.reason.question": "Ik heb een algemene vraag",
  "form.reason.collaboration": "Ik wil samenwerken", "form.reason.media": "Media of interview",
  "form.question.general": "Algemene informatie", "form.question.music": "Muziek en producties", "form.question.availability": "Beschikbaarheid",
  "form.question.technical": "Technische vraag", "form.question.other": "Anders", "form.collab.artist": "Artiest of event", "form.collab.brand": "Merk of organisatie",
  "form.collab.music": "Muzikale samenwerking", "form.collab.other": "Anders", "form.media.interview": "Interview", "form.media.press": "Persbericht", "form.media.photo": "Foto- of videovraag", "form.media.other": "Anders",
  "validation.name": "Vul je naam in.", "validation.nameLong": "Naam is te lang.", "validation.email": "Vul een geldig e-mailadres in.", "validation.phone": "Vul je telefoonnummer in.", "validation.phoneLong": "Telefoonnummer is te lang.", "validation.reason": "Kies waarvoor je contact opneemt.", "validation.eventType": "Kies een type evenement.", "validation.questionType": "Kies het onderwerp van je vraag.", "validation.collaborationType": "Kies het type samenwerking.", "validation.mediaType": "Kies het type media-aanvraag.", "validation.location": "Vul de locatie in.", "validation.locationLong": "Locatie is te lang.", "validation.message": "Vertel kort wat je zoekt (min. 20 tekens).", "validation.messageLong": "Bericht is te lang.",
  "gallery.filter": "Filter op jaar", "gallery.list": "Foto gallery", "gallery.all": "Alle", "gallery.none": "Geen foto's gevonden voor {year}.",
  "gallery.enlarge": "Vergroot: {alt}", "gallery.previous": "Vorige foto", "gallery.next": "Volgende foto", "gallery.photo": "Foto {current} van {total}",
  "videos.watch": "Bekijk: {title}", "videos.more": "Meer content op onze kanalen",
  "videos.follow": "Volg ons voor nieuwe uploads, live streams en exclusieve behind-the-scenes content.",
  "videos.youtube": "YouTube Kanaal", "videos.instagram": "Instagram Reels", "videos.close": "Sluiten video",
  "legal.privacy": "Privacybeleid", "legal.terms": "Voorwaarden", "legal.cookies": "Cookies", "legal.contact": "Contact",
  "terms.badge": "Juridisch", "terms.title": "Algemene Voorwaarden", "terms.version": "Versie augustus 2026",
  "terms.intro": "Door het boeken van DJ Cannix verklaart u akkoord te gaan met de volgende voorwaarden. Lees ze aandachtig door.",
  "privacy.title": "Privacy Policy", "privacy.updated": "Laatst bijgewerkt: augustus 2026",
  "privacy.intro": "Wij respecteren uw privacy en verbinden ons ertoe uw persoonsgegevens te beschermen in overeenstemming met de Algemene Verordening Gegevensbescherming (AVG / GDPR).",
  "cookies.title": "Cookiebeleid", "cookies.updated": "Laatst bijgewerkt: augustus 2026",
  "cookies.intro": "De website van DJ Cannix gebruikt enkel functionele cookies die strikt noodzakelijk zijn voor de werking van de site. Wij plaatsen geen tracking-, marketing- of analyticscookies zonder uw toestemming.",
  "cookies.what": "Wat zijn cookies?", "cookies.whatText": "Cookies zijn kleine tekstbestanden die op uw apparaat worden geplaatst wanneer u een website bezoekt. Ze worden gebruikt om de website correct te laten functioneren, uw voorkeuren te onthouden en het gebruik van de site te analyseren.",
  "cookies.which": "Welke cookies gebruiken we?", "cookies.manage": "Cookies beheren of verwijderen",
  "cookies.manageText": "U kunt cookies beheren via uw browserinstellingen. Let op: het uitschakelen van functionele cookies kan de werking van de website beïnvloeden. Raadpleeg de helpfunctie van uw browser voor meer informatie.",
  "cookies.contactText": "Voor vragen over ons cookiebeleid kunt u ons bereiken via",
  "modal.confirm": "Bevestigen", "modal.cancel": "Annuleren",
  "cookies.always": "Altijd actief", "cookies.inactive": "Niet actief", "cookies.examples": "Voorbeelden:", "cookies.duration": "Bewaarduur:",
  "footer.navigation": "Navigatie", "footer.country": "België (Europa)", "footer.rights": "Alle rechten voorbehouden.",
  "bio.short": "Cannix is een DJ & producer met meer dan 5 jaar ervaring. Als DJ beweegt hij tussen allround fuifmuziek, echte meezingers, harde remixes en Drum & Bass. Binnen DnB ligt zijn focus onder andere op Jump Up, terwijl ook Hardstyle en Jumpstyle deel uitmaken van zijn sound.\n\nWat hij ook draait of produceert, het doel blijft simpel: mensen laten bewegen, hun aandacht vasthouden en energie creëren.",
  "bio.long.1": "Cannix is een Belgische DJ & producer die al meer dan 5 jaar actief is in de muziekwereld. Als DJ beweegt hij tussen verschillende stijlen en settings. Van allround fuiven met herkenbare meezingers en bekende feestplaten tot harde remixes en energieke Drum & Bass.",
  "bio.long.2": "Binnen Drum & Bass ligt zijn focus onder andere op Jump Up. Daarnaast maken ook Hardstyle en Jumpstyle deel uit van zijn muzikale stijl. Door die brede interesse kan Cannix zich aanpassen aan verschillende soorten publiek en events, zonder de energie uit het oog te verliezen.",
  "bio.long.3": "Naast DJ'en is Cannix ook actief als producer. In de studio werkt hij aan zijn eigen sound en experimenteert hij voortdurend met nieuwe muziek, sounds en ideeën.",
  "bio.long.4": "Of hij nu achter de draaitafels staat of in de studio zit, het doel blijft hetzelfde: mensen laten bewegen, hun aandacht vasthouden en een sfeer creëren die blijft hangen.",
  "video.1.title": "Mexican Wave Party 2026 - Highlights", "video.1.description": "Energieke set tijdens Mexican Wave Party 2026 met het volle publiek in de pit.",
  "video.2.title": "Silent Disco 2025 - Full Set", "video.2.description": "Unieke silent disco ervaring waar iedereen op zijn eigen frequentie danst.",
  "video.3.title": "PEMP 2024 - DJ Cannix Live", "video.3.description": "Live opname van het PEMP festival 2024.",
  "video.4.title": "Blacklight Party 2024", "video.4.description": "Neon vibes en blacklight energy met DJ Cannix.",
  "video.5.title": "Mexican Wave Party 2024", "video.5.description": "Een van de grootste Mexican Wave edities ooit.",
  "video.6.title": "'t Leerke 2025 - Aftermovie", "video.6.description": "Aftermovie van een onvergetelijke avond in 't Leerke.",
  "terms.s1": "1. Toepassingsgebied|Deze algemene voorwaarden zijn van toepassing op alle offertes, overeenkomsten en boekingen met Cannix (hierna 'Artiest'). Door een boeking te bevestigen, aanvaardt de klant (hierna 'Opdrachtgever') deze voorwaarden volledig.",
  "terms.s2": "2. Boeking & Bevestiging|Een boeking is pas definitief na schriftelijke bevestiging (e-mail) door de Artiest én de ontvangst van het gevraagde voorschot (indien van toepassing). Mondelinge afspraken zijn niet bindend zonder schriftelijke bevestiging.",
  "terms.s3": "3. Gage & Betalingsvoorwaarden|De gage wordt vastgelegd in de offerte en/of overeenkomst. Een voorschot van 25% is verschuldigd bij bevestiging. Het saldo dient uiterlijk 7 dagen vóór het optreden te worden voldaan, tenzij anders overeengekomen. Alle vermelde bedragen zijn exclusief BTW tenzij anders aangegeven.",
  "terms.s4": "4. Annulatie door de Opdrachtgever|Bij annulatie meer dan 30 dagen voor de datum: 25% van de gage. Tussen 14 en 30 dagen: 50% van de gage. Minder dan 14 dagen voor de datum: 100% van de gage is verschuldigd. Annulaties dienen schriftelijk te worden meegedeeld.",
  "terms.s5": "5. Annulatie door de Artiest|De Artiest behoudt het recht een boeking te annuleren wegens overmacht (ziekte, familiale omstandigheden, overheidsbevel). In dat geval wordt het volledige voorschot terugbetaald. De Artiest zal trachten een vervanger aan te bevelen.",
  "terms.s6": "6. Technische Rider|De Opdrachtgever zorgt voor de technische vereisten zoals vastgelegd in de rider (geluidsinstallatie, verlichting, speelruimte). Indien de vereisten niet beschikbaar zijn, behoudt de Artiest het recht de gage aan te passen of het optreden te weigeren zonder teruggave.",
  "terms.s7": "7. Auteursrecht & Opnames|Opnames (audio/video) van het optreden voor commercieel gebruik zijn slechts toegestaan met schriftelijke toestemming van de Artiest. Het gebruik van beeldmateriaal op sociale media voor promotionele doeleinden van het event is vrij.",
  "terms.s8": "8. Aansprakelijkheid|De Artiest is niet aansprakelijk voor schade ten gevolge van overmacht, technische storingen buiten zijn controle, of het handelen van derden. De aansprakelijkheid van de Artiest is in elk geval beperkt tot het bedrag van de overeengekomen gage.",
  "terms.s9": "9. Toepasselijk recht|Op alle overeenkomsten met Cannix is het Belgisch recht van toepassing. Geschillen worden voorgelegd aan de bevoegde rechtbanken van het arrondissement van de vestigingsplaats van de Artiest.",
  "privacy.s1": "1. Wie zijn wij?|Cannix (hierna 'wij', 'ons' of 'onze') is een muzikale onderneming actief als DJ en entertainer, gevestigd in België. Wij verwerken persoonsgegevens in het kader van boekingsaanvragen en communicatie.",
  "privacy.s2": "2. Welke gegevens verzamelen we?|Via ons contactformulier verzamelen wij: naam, e-mailadres, telefoonnummer (optioneel), type evenement, datum en locatie, en de inhoud van uw bericht. Deze gegevens worden uitsluitend gebruikt om uw boeking te behandelen.",
  "privacy.s3": "3. Doel van de verwerking|Uw gegevens worden verwerkt voor: het beantwoorden van boekingsaanvragen, het opmaken van offertes, en het versturen van contracten en facturen. We gebruiken uw gegevens nooit voor commerciële e-mailcampagnes zonder uw uitdrukkelijke toestemming.",
  "privacy.s4": "4. Hoe lang bewaren we uw gegevens?|We bewaren uw persoonsgegevens niet langer dan noodzakelijk voor het doel waarvoor ze zijn verzameld. Contactformulierdata wordt maximaal 2 jaar bewaard. Boeking- en facturatiegegevens bewaren we 7 jaar conform de Belgische boekhoudwetgeving.",
  "privacy.s5": "5. Delen met derden|Wij delen uw gegevens niet met derden, tenzij dit noodzakelijk is voor de uitvoering van de overeenkomst (bijv. locatie, technische partners) of wettelijk verplicht. Wij maken geen gebruik van tracking-cookies of advertentie-netwerken.",
  "privacy.s6": "6. Uw rechten|U heeft het recht op inzage, rectificatie, verwijdering en overdraagbaarheid van uw persoonsgegevens. U kunt ook bezwaar maken tegen de verwerking. Neem hiervoor contact op via bookings@cannix.be.",
  "privacy.s7": "7. Contact & klachten|Voor vragen over dit beleid kunt u ons bereiken via bookings@cannix.be. U heeft ook het recht een klacht in te dienen bij de Gegevensbeschermingsautoriteit (GBA): www.gegevensbeschermingsautoriteit.be.",
  "cookies.functional": "Functionele cookies|Noodzakelijk voor het functioneren van de website (sessiebeheer, navigatie). Deze cookies kunnen niet uitgeschakeld worden.|Sessie-ID, taalvoorkeur, navigatiestaat|Sessie / max. 1 jaar",
  "cookies.analytics": "Analytische cookies|Helpen ons begrijpen hoe bezoekers de website gebruiken. Wij gebruiken momenteel geen externe analytische diensten (geen Google Analytics).|Geen externe trackers actief|Niet van toepassing",
  "cookies.marketing": "Marketing cookies|Wij plaatsen geen marketing- of advertentiecookies. Er worden geen gegevens gedeeld met advertentienetwerken.|Geen advertentiecookies|Niet van toepassing",
} as const;

type TranslationKey = keyof typeof nl;
type Dictionary = Record<TranslationKey, string>;

const en: Dictionary = {
  ...nl,
  "nav.about": "About", "nav.gallery": "Gallery", "nav.videos": "Videos", "nav.mobile": "Mobile navigation",
  "nav.main": "Main navigation", "nav.open": "Open menu", "nav.close": "Close menu", "nav.language": "Choose language",
  "header.home": "Cannix home", "booking": "Book Cannix", "language.label": "Language", "cookie.title": "We use cookies 🍪",
  "cookie.description": "This website uses functional cookies for an optimal experience. No tracking or external analytics services.",
  "cookie.more": "Read more", "cookie.accept": "Accept", "cookie.decline": "Decline", "close": "Close",
  "splash.welcome": "Welcome screen", "splash.continue": "Continue", "splash.continueLabel": "Continue to the website",
  "notFound.title": "Page not found", "notFound.description": "The page you're looking for does not exist or has moved. No worries — the beat goes on.", "notFound.home": "Back to Home",
  "home.nextGig": "Next gig", "home.description": "Belgian DJ specialising in energetic festival sets, party classics, singalongs and hard remixes.",
  "home.nextEvent": "Next event", "home.tickets": "Tickets & Info", "home.about": "About Cannix", "home.musicConnects": "Music that connects",
  "home.readMore": "Read more", "home.bookingsOpen": "Bookings open", "home.availability": "Request availability", "home.contact": "Get in touch",
  "home.genres": "Genres", "home.follow": "Follow the vibe", "home.stats.age": "Age", "home.stats.experience": "Years experience",
  "home.stats.shows": "Shows", "home.stats.festivals": "Festivals", "home.stats.countries": "Countries",
  "about.title": "Energy, Beats & Unique Atmosphere", "about.subtitle": "Passion for moving the dance floor, from singalongs and party classics to hard DnB & hardstyle.",
  "about.musicStyle": "My Music & Style", "about.style1": "As an all-round DJ I mainly play recognisable party music, singalongs and harder remixes. I also play and produce Drum & Bass, with a focus on Jump Up. Hardstyle and Jumpstyle regularly feature in my sets too.",
  "about.style2": "I am always looking for new music and new sounds. What I play depends on the audience, the location and the atmosphere of the moment. The most important thing is keeping people moving and engaged with the music.",
  "about.figures": "Numbers", "about.bookings": "Bookings & Contact", "about.interest": "Interested in a booking? Feel free to send a message for more information and availability.",
  "about.drives": "What drives it", "about.drivesText": "For me, DJing is mainly about the atmosphere and the audience.",
  "about.energy": "Energy", "about.energyText": "A good set should give energy and keep the dance floor moving.",
  "about.music": "Music", "about.musicText": "From familiar singalongs to DnB and harder remixes. I love discovering new music.",
  "about.audience": "Audience", "about.audienceText": "I read the room and respond to what is happening. The audience helps shape the direction.",
  "contact.title": "Contact & Collaboration", "contact.heading": "Let's work together", "contact.intro": "Do you have a booking request, general question, collaboration idea or media request? Fill in the form and we will get back to you within 24 hours.",
  "contact.send": "Send a message", "contact.direct": "Direct contact", "contact.bookings": "Contact & bookings", "contact.phone": "Phone",
  "contact.location": "Location", "contact.locationValue": "Belgium (bookable across Europe)", "contact.whatNeed": "What we need",
  "contact.needIntro": "These details help us prepare a suitable proposal:", "contact.date": "Date & time", "contact.venue": "Location / venue",
  "contact.attendees": "Expected number of guests", "contact.vibe": "Musical direction / vibe", "contact.budget": "Budget indication", "contact.socials": "Socials",
  "contact.faq": "Frequently asked questions", "contact.faqIntro": "The most common questions about contact and bookings.",
  "faq.1q": "How far in advance should I book?", "faq.1a": "For weekends and festivals we recommend booking 2–3 months ahead. Weekdays and last-minute bookings may be possible depending on the schedule.",
  "faq.2q": "What is the price of a set?", "faq.2a": "Prices vary based on duration, location, day, equipment and whether it is a club, festival or private event. Send a request for a tailored quote.",
  "faq.3q": "Do you bring your own equipment?", "faq.3a": "I normally play on the house gear (CDJ-3000 / mixer). Discuss specific riders or your own controller in advance.",
  "faq.4q": "Do you play weddings or corporate events?", "faq.4a": "Absolutely. I have plenty of private-event experience and adapt the music to the organiser's desired atmosphere.",
  "faq.5q": "How far do you travel?", "faq.5a": "From Belgium across Europe. Travel and accommodation costs are added for performances outside Belgium.",
  "faq.6q": "Can I hear a demo or live set?", "faq.6a": "Of course. Listen to mixes and productions on SoundCloud or request a live demo through the form.",
  "form.name": "Name", "form.namePlaceholder": "Your name", "form.email": "Email", "form.website": "Website", "form.reason": "What are you contacting us about?",
  "form.choose": "Make a choice", "form.phone": "Phone", "form.eventType": "Event type", "form.eventChoose": "Choose an event type",
  "form.questionSubject": "Subject of your question", "form.collaborationType": "Type of collaboration", "form.mediaType": "Type of media request", "form.date": "Date",
  "form.optional": "Optional", "form.location": "Location", "form.locationPlaceholder": "City / venue", "form.message": "Message",
  "form.messagePlaceholder": "Briefly tell us about your event, timing, expected number of guests and what you are looking for.", "form.send": "Send request", "form.sending": "Sending...",
  "form.error": "Could not send.", "form.retry": "Try again or email bookings@cannix.be directly.", "form.successTitle": "Request sent", "form.thanks": "Thank you for your request.", "form.successText": "We will get in touch as soon as possible.",
  "form.event.club": "Club night", "form.event.festival": "Festival", "form.event.party": "Party", "form.event.rave": "Rave", "form.event.private": "Private party", "form.event.wedding": "Wedding", "form.event.other": "Other",
  "form.reason.booking": "I want to book Cannix", "form.reason.question": "I have a general question", "form.reason.collaboration": "I want to collaborate", "form.reason.media": "Media or interview",
  "form.question.general": "General information", "form.question.music": "Music and productions", "form.question.availability": "Availability", "form.question.technical": "Technical question", "form.question.other": "Other",
  "form.collab.artist": "Artist or event", "form.collab.brand": "Brand or organisation", "form.collab.music": "Musical collaboration", "form.collab.other": "Other", "form.media.interview": "Interview", "form.media.press": "Press release", "form.media.photo": "Photo or video request", "form.media.other": "Other",
  "validation.name": "Enter your name.", "validation.nameLong": "Name is too long.", "validation.email": "Enter a valid email address.", "validation.phone": "Enter your phone number.", "validation.phoneLong": "Phone number is too long.", "validation.reason": "Choose what you are contacting us about.", "validation.eventType": "Choose an event type.", "validation.questionType": "Choose the subject of your question.", "validation.collaborationType": "Choose the type of collaboration.", "validation.mediaType": "Choose the type of media request.", "validation.location": "Enter the location.", "validation.locationLong": "Location is too long.", "validation.message": "Briefly tell us what you are looking for (min. 20 characters).", "validation.messageLong": "Message is too long.",
  "gallery.filter": "Filter by year", "gallery.list": "Photo gallery", "gallery.all": "All", "gallery.none": "No photos found for {year}.", "gallery.enlarge": "Enlarge: {alt}", "gallery.previous": "Previous photo", "gallery.next": "Next photo", "gallery.photo": "Photo {current} of {total}",
  "videos.watch": "Watch: {title}", "videos.more": "More content on our channels", "videos.follow": "Follow us for new uploads, live streams and exclusive behind-the-scenes content.", "videos.youtube": "YouTube Channel", "videos.instagram": "Instagram Reels", "videos.close": "Close video",
  "legal.privacy": "Privacy", "legal.terms": "Terms", "legal.cookies": "Cookies", "legal.contact": "Contact", "terms.badge": "Legal", "terms.title": "Terms & Conditions", "terms.version": "Version August 2026", "terms.intro": "By booking DJ Cannix you agree to the following terms. Please read them carefully.",
  "privacy.title": "Privacy Policy", "privacy.updated": "Last updated: August 2026", "privacy.intro": "We respect your privacy and are committed to protecting your personal data in accordance with the General Data Protection Regulation (GDPR).",
  "cookies.title": "Cookie Policy", "cookies.updated": "Last updated: August 2026", "cookies.intro": "The DJ Cannix website only uses functional cookies that are strictly necessary for the site to work. We do not place tracking, marketing or analytics cookies without your consent.",
  "cookies.what": "What are cookies?", "cookies.whatText": "Cookies are small text files placed on your device when you visit a website. They help the website function correctly, remember your preferences and analyse site usage.", "cookies.which": "Which cookies do we use?", "cookies.manage": "Managing or deleting cookies", "cookies.manageText": "You can manage cookies through your browser settings. Please note that disabling functional cookies may affect how the website works. Consult your browser's help function for more information.", "cookies.always": "Always active", "cookies.inactive": "Inactive", "cookies.examples": "Examples:", "cookies.duration": "Duration:",
  "cookies.contactText": "For questions about our cookie policy, contact us at", "modal.confirm": "Confirm", "modal.cancel": "Cancel",
  "footer.navigation": "Navigation", "footer.country": "Belgium (Europe)", "footer.rights": "All rights reserved.",
  "bio.long.1": "Cannix is a Belgian DJ & producer who has been active in the music world for over 5 years. As a DJ he moves between different styles and settings, from all-round parties with recognisable singalongs and party records to hard remixes and energetic Drum & Bass.",
  "bio.long.2": "Within Drum & Bass his focus includes Jump Up. Hardstyle and Jumpstyle are also part of his musical style. This broad interest lets Cannix adapt to different audiences and events without losing sight of the energy.",
  "bio.long.3": "Besides DJing, Cannix is also active as a producer. In the studio he works on his own sound and continually experiments with new music, sounds and ideas.",
  "bio.long.4": "Whether behind the decks or in the studio, the goal remains the same: make people move, hold their attention and create an atmosphere that stays with them.",
  "bio.short": "Cannix is a DJ & producer with over 5 years of experience. He moves between all-round party music, singalongs, hard remixes and Drum & Bass, with Jump Up, Hardstyle and Jumpstyle also part of his sound.\n\nWhatever he plays or produces, the goal is simple: make people move, hold their attention and create energy.",
  "video.1.title": "Mexican Wave Party 2026 - Highlights", "video.1.description": "An energetic set during Mexican Wave Party 2026 with the crowd in the pit.", "video.2.title": "Silent Disco 2025 - Full Set", "video.2.description": "A unique silent disco experience where everyone dances to their own frequency.", "video.3.title": "PEMP 2024 - DJ Cannix Live", "video.3.description": "Live recording from the 2024 PEMP festival.", "video.4.title": "Blacklight Party 2024", "video.4.description": "Neon vibes and blacklight energy with DJ Cannix.", "video.5.title": "Mexican Wave Party 2024", "video.5.description": "One of the biggest Mexican Wave editions ever.", "video.6.title": "'t Leerke 2025 - Aftermovie", "video.6.description": "Aftermovie of an unforgettable night at 't Leerke.",
  "terms.s1": "1. Scope|These terms apply to all quotes, agreements and bookings with Cannix (the Artist). Confirming a booking means the client accepts these terms in full.",
  "terms.s2": "2. Booking & Confirmation|A booking is final only after written confirmation by the Artist and receipt of any requested deposit. Verbal agreements are not binding without written confirmation.",
  "terms.s3": "3. Fee & Payment|The fee is set out in the quote or agreement. A 25% deposit is due on confirmation; the balance is due no later than 7 days before the performance unless agreed otherwise. Amounts exclude VAT unless stated otherwise.",
  "terms.s4": "4. Cancellation by Client|For cancellation more than 30 days before the date: 25% of the fee. Between 14 and 30 days: 50%. Less than 14 days: 100% is due. Cancellations must be communicated in writing.",
  "terms.s5": "5. Cancellation by Artist|The Artist may cancel due to force majeure (illness, family circumstances or government order). In that case the full deposit is refunded and the Artist will try to recommend a replacement.",
  "terms.s6": "6. Technical Rider|The Client provides the technical requirements in the rider (sound system, lighting and performance space). If unavailable, the Artist may adjust the fee or refuse the performance without refund.",
  "terms.s7": "7. Copyright & Recordings|Audio or video recordings for commercial use require written permission from the Artist. Social-media imagery for the event's promotion is permitted.",
  "terms.s8": "8. Liability|The Artist is not liable for damage caused by force majeure, technical failures outside their control or third parties. Liability is limited to the agreed fee.",
  "terms.s9": "9. Governing Law|Belgian law applies to all agreements with Cannix. Disputes are submitted to the competent courts of the Artist's registered location.",
  "privacy.s1": "1. Who are we?|Cannix is a musical business operating as a DJ and entertainer in Belgium. We process personal data for booking requests and communication.",
  "privacy.s2": "2. What data do we collect?|Our contact form collects name, email, phone number, event type, date, location and message content. This data is used only to handle your booking.",
  "privacy.s3": "3. Purpose of processing|Your data is processed to answer booking requests, prepare quotes and send contracts and invoices. We never use it for commercial email campaigns without your explicit consent.",
  "privacy.s4": "4. How long do we keep your data?|We keep personal data no longer than necessary. Contact-form data is kept for up to 2 years; booking and invoicing data for 7 years as required by Belgian accounting law.",
  "privacy.s5": "5. Sharing with third parties|We do not share your data unless necessary to perform the agreement or legally required. We do not use tracking cookies or advertising networks.",
  "privacy.s6": "6. Your rights|You have the right to access, rectify, erase and transfer your personal data, and to object to processing. Contact bookings@cannix.be.",
  "privacy.s7": "7. Contact & complaints|For questions, contact bookings@cannix.be. You may also complain to the Belgian Data Protection Authority.",
  "cookies.functional": "Functional cookies|Necessary for the website to function (session management and navigation). These cookies cannot be disabled.|Session ID, language preference, navigation state|Session / max. 1 year",
  "cookies.analytics": "Analytics cookies|Help us understand how visitors use the website. We currently use no external analytics services.|No external trackers active|Not applicable",
  "cookies.marketing": "Marketing cookies|We do not place marketing or advertising cookies, and share no data with advertising networks.|No advertising cookies|Not applicable",
};

const fr: Dictionary = { ...en,
  "nav.home": "Accueil", "nav.about": "À propos", "nav.gallery": "Photos", "nav.contact": "Contact", "nav.videos": "Vidéos", "nav.main": "Navigation principale", "nav.mobile": "Navigation mobile", "nav.language": "Choisir la langue", "booking": "Réserver Cannix", "language.label": "Langue",
  "cookie.title": "Nous utilisons des cookies 🍪", "cookie.description": "Ce site utilise des cookies fonctionnels pour une expérience optimale. Aucun suivi ni service d'analyse externe.", "cookie.more": "En savoir plus", "cookie.accept": "Accepter", "cookie.decline": "Refuser",
  "splash.welcome": "Écran d'accueil", "splash.continue": "Continuer", "splash.continueLabel": "Continuer vers le site",
  "notFound.title": "Page introuvable", "notFound.description": "La page demandée n'existe pas ou a été déplacée. Pas d'inquiétude — le beat continue.", "notFound.home": "Retour à l'accueil",
  "home.nextGig": "Prochain gig", "home.description": "DJ belge spécialisé dans les sets de festival énergiques, les classiques de fête, les refrains et les remixes percutants.", "home.nextEvent": "Prochain événement", "home.tickets": "Billets & Infos", "home.musicConnects": "La musique qui rassemble", "home.readMore": "En savoir plus", "home.bookingsOpen": "Réservations ouvertes", "home.availability": "Demander les disponibilités", "home.contact": "Nous contacter", "home.follow": "Suivez la vibe", "home.stats.age": "Âge", "home.stats.experience": "Années d'expérience", "home.stats.shows": "Prestations", "home.stats.festivals": "Festivals", "home.stats.countries": "Pays",
  "about.title": "Énergie, Beats & Ambiance unique", "about.subtitle": "La passion de faire vibrer la piste, des refrains et classiques de fête à la DnB & hardstyle.", "about.musicStyle": "Ma musique & mon style", "about.figures": "Chiffres", "about.bookings": "Réservations & Contact", "about.interest": "Intéressé par une réservation ? Envoyez un message pour plus d'informations et les disponibilités.", "about.drives": "Ce qui compte", "about.drivesText": "Pour moi, être DJ, c'est avant tout l'ambiance et le public.", "about.energy": "Énergie", "about.energyText": "Un bon set doit donner de l'énergie et faire bouger la piste.", "about.music": "Musique", "about.musicText": "Des refrains connus à la DnB et aux remixes percutants. J'aime découvrir de nouvelles musiques.", "about.audience": "Public", "about.audienceText": "J'observe la salle et réagis à ce qui se passe. Le public contribue à la direction.",
  "contact.title": "Contact & Collaboration", "contact.heading": "Travaillons ensemble", "contact.intro": "Une demande de réservation, une question, une idée de collaboration ou une demande média ? Remplissez le formulaire et nous vous répondrons sous 24 h.", "contact.send": "Envoyer un message", "contact.direct": "Contact direct", "contact.bookings": "Contact & réservations", "contact.phone": "Téléphone", "contact.location": "Lieu", "contact.locationValue": "Belgique (réservable en Europe)", "contact.whatNeed": "Ce dont nous avons besoin", "contact.needIntro": "Ces informations nous aident à préparer une proposition adaptée :", "contact.date": "Date & heure", "contact.venue": "Lieu / salle", "contact.attendees": "Nombre de visiteurs attendu", "contact.vibe": "Direction musicale / vibe", "contact.budget": "Indication de budget", "contact.socials": "Réseaux sociaux", "contact.faq": "Questions fréquentes", "contact.faqIntro": "Les questions les plus fréquentes sur le contact et les réservations.",
  "faq.1q": "Combien de temps à l'avance faut-il réserver ?", "faq.1a": "Pour les week-ends et festivals, nous recommandons 2 à 3 mois à l'avance. Les jours de semaine et demandes de dernière minute sont parfois possibles.",
  "faq.2q": "Quel est le prix d'un set ?", "faq.2a": "Les prix varient selon la durée, le lieu, le jour, le matériel et le type d'événement. Envoyez une demande pour un devis personnalisé.",
  "faq.3q": "Apportez-vous votre propre matériel ?", "faq.3a": "Je joue généralement sur le matériel de la salle (CDJ-3000 / mixer). Discutez des besoins spécifiques à l'avance.",
  "faq.4q": "Jouez-vous aussi pour des mariages ou événements d'entreprise ?", "faq.4a": "Absolument. J'ai une grande expérience des événements privés et j'adapte la musique à l'ambiance souhaitée.",
  "faq.5q": "Jusqu'où vous déplacez-vous ?", "faq.5a": "Depuis la Belgique dans toute l'Europe. Les frais de déplacement et de séjour s'ajoutent hors Belgique.",
  "faq.6q": "Puis-je écouter une démo ou un live ?", "faq.6a": "Bien sûr. Écoutez les mixes et productions sur SoundCloud ou demandez une démo via le formulaire.",
  "form.name": "Nom", "form.namePlaceholder": "Votre nom", "form.email": "E-mail", "form.website": "Site web", "form.reason": "Pourquoi nous contactez-vous ?", "form.choose": "Choisissez", "form.phone": "Téléphone", "form.eventType": "Type d'événement", "form.eventChoose": "Choisissez un type d'événement", "form.questionSubject": "Sujet de votre question", "form.collaborationType": "Type de collaboration", "form.mediaType": "Type de demande média", "form.date": "Date", "form.optional": "Facultatif", "form.location": "Lieu", "form.locationPlaceholder": "Ville / salle", "form.message": "Message", "form.messagePlaceholder": "Décrivez brièvement votre événement, l'horaire, le nombre de visiteurs prévu et ce que vous recherchez.", "form.send": "Envoyer la demande", "form.sending": "Envoi...", "form.error": "Échec de l'envoi.", "form.retry": "Réessayez ou envoyez un e-mail à bookings@cannix.be.", "form.successTitle": "Demande envoyée", "form.thanks": "Merci pour votre demande.", "form.successText": "Nous vous contacterons dès que possible.",
  "form.event.club": "Soirée club", "form.event.festival": "Festival", "form.event.party": "Fête", "form.event.rave": "Rave", "form.event.private": "Fête privée", "form.event.wedding": "Mariage", "form.event.other": "Autre", "form.reason.booking": "Je veux réserver Cannix", "form.reason.question": "J'ai une question générale", "form.reason.collaboration": "Je veux collaborer", "form.reason.media": "Média ou interview", "form.question.general": "Informations générales", "form.question.music": "Musique et productions", "form.question.availability": "Disponibilités", "form.question.technical": "Question technique", "form.question.other": "Autre", "form.collab.artist": "Artiste ou événement", "form.collab.brand": "Marque ou organisation", "form.collab.music": "Collaboration musicale", "form.collab.other": "Autre", "form.media.interview": "Interview", "form.media.press": "Communiqué de presse", "form.media.photo": "Demande photo ou vidéo", "form.media.other": "Autre",
  "gallery.filter": "Filtrer par année", "gallery.list": "Galerie photos", "gallery.all": "Toutes", "gallery.none": "Aucune photo trouvée pour {year}.", "gallery.enlarge": "Agrandir : {alt}", "gallery.previous": "Photo précédente", "gallery.next": "Photo suivante", "gallery.photo": "Photo {current} sur {total}", "videos.more": "Plus de contenu sur nos chaînes", "videos.follow": "Suivez-nous pour de nouvelles vidéos, des lives et des contenus exclusifs en coulisses.", "videos.youtube": "Chaîne YouTube", "videos.instagram": "Reels Instagram", "videos.close": "Fermer la vidéo",
  "legal.privacy": "Confidentialité", "legal.terms": "Conditions", "legal.cookies": "Cookies", "legal.contact": "Contact", "terms.badge": "Juridique", "terms.title": "Conditions générales", "terms.version": "Version août 2026", "terms.intro": "En réservant DJ Cannix, vous acceptez les conditions suivantes. Lisez-les attentivement.", "privacy.updated": "Dernière mise à jour : août 2026", "privacy.intro": "Nous respectons votre vie privée et nous engageons à protéger vos données personnelles conformément au RGPD.", "cookies.title": "Politique relative aux cookies", "cookies.updated": "Dernière mise à jour : août 2026", "cookies.intro": "Le site de DJ Cannix utilise uniquement des cookies fonctionnels strictement nécessaires. Aucun cookie de suivi, marketing ou analytique n'est placé sans votre consentement.", "cookies.what": "Que sont les cookies ?", "cookies.whatText": "Les cookies sont de petits fichiers texte placés sur votre appareil lors de la visite d'un site. Ils permettent au site de fonctionner correctement et de mémoriser vos préférences.", "cookies.which": "Quels cookies utilisons-nous ?", "cookies.manage": "Gérer ou supprimer les cookies", "cookies.manageText": "Vous pouvez gérer les cookies dans les paramètres de votre navigateur. La désactivation des cookies fonctionnels peut affecter le fonctionnement du site.", "cookies.always": "Toujours actif", "cookies.inactive": "Inactif", "cookies.examples": "Exemples :", "cookies.duration": "Durée :",
  "cookies.contactText": "Pour toute question sur notre politique de cookies, contactez-nous à", "modal.confirm": "Confirmer", "modal.cancel": "Annuler",
  "about.style1": "En tant que DJ généraliste, je joue des musiques de fête reconnaissables, des refrains et des remixes percutants. Je joue et produis aussi de la Drum & Bass, notamment du Jump Up, ainsi que de la Hardstyle et de la Jumpstyle.", "about.style2": "Je cherche toujours de nouvelles musiques et de nouveaux sons. Je m'adapte au public, au lieu et à l'ambiance du moment pour garder les gens en mouvement.", "bio.long.1": "Cannix est un DJ et producteur belge actif depuis plus de 5 ans. Il navigue entre différents styles et ambiances, des fêtes généralistes aux remixes percutants et à la Drum & Bass énergique.", "bio.long.2": "En Drum & Bass, son univers inclut notamment le Jump Up, ainsi que la Hardstyle et la Jumpstyle. Cette ouverture lui permet de s'adapter à chaque public et événement.", "bio.long.3": "En plus du DJing, Cannix produit sa propre musique et expérimente constamment de nouveaux sons et de nouvelles idées.", "bio.long.4": "Derrière les platines comme en studio, l'objectif reste le même : faire bouger les gens et créer une ambiance mémorable.",
  "terms.s1": "1. Champ d'application|Ces conditions s'appliquent à tous les devis, accords et réservations avec Cannix. La confirmation d'une réservation implique leur acceptation complète.", "terms.s2": "2. Réservation & confirmation|Une réservation est définitive après confirmation écrite et réception de l'acompte éventuel. Les accords verbaux ne sont pas contraignants.", "terms.s3": "3. Cachet & paiement|Le cachet figure dans le devis. Un acompte de 25 % est dû à la confirmation et le solde au plus tard 7 jours avant la prestation, sauf accord contraire.", "terms.s4": "4. Annulation par le client|Plus de 30 jours : 25 % du cachet. De 14 à 30 jours : 50 %. Moins de 14 jours : 100 %. Toute annulation doit être communiquée par écrit.", "terms.s5": "5. Annulation par l'artiste|L'artiste peut annuler en cas de force majeure. L'acompte est alors remboursé intégralement et un remplaçant peut être recommandé.", "terms.s6": "6. Fiche technique|Le client fournit les exigences techniques indiquées. Si elles ne sont pas disponibles, l'artiste peut adapter le cachet ou refuser la prestation.", "terms.s7": "7. Droits d'auteur & enregistrements|Les enregistrements à usage commercial nécessitent l'autorisation écrite de l'artiste. Les images promotionnelles de l'événement sur les réseaux sociaux sont autorisées.", "terms.s8": "8. Responsabilité|L'artiste n'est pas responsable des dommages dus à la force majeure, aux pannes hors de son contrôle ou à des tiers. La responsabilité est limitée au cachet convenu.", "terms.s9": "9. Droit applicable|Le droit belge s'applique à tous les accords avec Cannix. Les litiges relèvent des tribunaux compétents du siège de l'artiste.",
  "privacy.s1": "1. Qui sommes-nous ?|Cannix est une entreprise musicale active comme DJ et artiste en Belgique. Nous traitons des données personnelles pour les demandes de réservation et la communication.", "privacy.s2": "2. Quelles données collectons-nous ?|Le formulaire collecte le nom, l'e-mail, le téléphone, le type d'événement, la date, le lieu et le message, uniquement pour traiter la réservation.", "privacy.s3": "3. Finalité du traitement|Les données servent à répondre aux demandes, préparer les devis et envoyer contrats et factures. Elles ne servent jamais à des campagnes commerciales sans consentement.", "privacy.s4": "4. Combien de temps conservons-nous vos données ?|Les données sont conservées uniquement le temps nécessaire : jusqu'à 2 ans pour les formulaires et 7 ans pour les données comptables.", "privacy.s5": "5. Partage avec des tiers|Nous ne partageons pas vos données sauf nécessité contractuelle ou obligation légale. Aucun cookie de suivi ni réseau publicitaire n'est utilisé.", "privacy.s6": "6. Vos droits|Vous pouvez accéder à vos données, les rectifier, les effacer ou les transférer, et vous opposer au traitement. Contact : bookings@cannix.be.", "privacy.s7": "7. Contact & réclamations|Pour toute question, contactez bookings@cannix.be. Vous pouvez également introduire une réclamation auprès de l'autorité belge de protection des données.",
  "cookies.functional": "Cookies fonctionnels|Nécessaires au fonctionnement du site. Ils ne peuvent pas être désactivés.|Identifiant de session, langue, navigation|Session / 1 an max.", "cookies.analytics": "Cookies analytiques|Nous n'utilisons actuellement aucun service d'analyse externe.|Aucun traceur externe|Sans objet", "cookies.marketing": "Cookies marketing|Nous ne plaçons aucun cookie marketing ou publicitaire.|Aucun cookie publicitaire|Sans objet",
  "bio.short": "Cannix est DJ et producteur avec plus de 5 ans d'expérience. Il navigue entre musique de fête, refrains, remixes percutants et Drum & Bass, avec aussi du Jump Up, de la Hardstyle et de la Jumpstyle.\n\nSon objectif est simple : faire bouger les gens, capter leur attention et créer de l'énergie.", "video.1.title": "Mexican Wave Party 2026 - Highlights", "video.1.description": "Un set énergique au Mexican Wave Party 2026 avec un public déchaîné.", "video.2.title": "Silent Disco 2025 - Full Set", "video.2.description": "Une expérience silent disco unique où chacun danse sur sa propre fréquence.", "video.3.title": "PEMP 2024 - DJ Cannix Live", "video.3.description": "Enregistrement live du festival PEMP 2024.", "video.4.title": "Blacklight Party 2024", "video.4.description": "Vibes néon et énergie blacklight avec DJ Cannix.", "video.5.title": "Mexican Wave Party 2024", "video.5.description": "L'une des plus grandes éditions de Mexican Wave.", "video.6.title": "'t Leerke 2025 - Aftermovie", "video.6.description": "Aftermovie d'une soirée inoubliable au 't Leerke.",
  "validation.name": "Indiquez votre nom.", "validation.nameLong": "Le nom est trop long.", "validation.email": "Indiquez une adresse e-mail valide.", "validation.phone": "Indiquez votre numéro de téléphone.", "validation.phoneLong": "Le numéro est trop long.", "validation.reason": "Choisissez le motif du contact.", "validation.eventType": "Choisissez un type d'événement.", "validation.questionType": "Choisissez le sujet de votre question.", "validation.collaborationType": "Choisissez le type de collaboration.", "validation.mediaType": "Choisissez le type de demande média.", "validation.location": "Indiquez le lieu.", "validation.locationLong": "Le lieu est trop long.", "validation.message": "Décrivez brièvement votre demande (20 caractères min.).", "validation.messageLong": "Le message est trop long.",
};

const de: Dictionary = { ...en,
  "nav.home": "Startseite", "nav.about": "Über Cannix", "nav.gallery": "Fotos", "nav.contact": "Kontakt", "nav.videos": "Videos", "nav.main": "Hauptnavigation", "nav.mobile": "Mobile Navigation", "nav.language": "Sprache wählen", "booking": "Cannix buchen", "language.label": "Sprache",
  "cookie.title": "Wir verwenden Cookies 🍪", "cookie.description": "Diese Website verwendet funktionale Cookies für ein optimales Erlebnis. Kein Tracking und keine externen Analysedienste.", "cookie.more": "Mehr erfahren", "cookie.accept": "Akzeptieren", "cookie.decline": "Ablehnen",
  "splash.welcome": "Willkommensbildschirm", "splash.continue": "Weiter", "splash.continueLabel": "Zur Website weiter",
  "notFound.title": "Seite nicht gefunden", "notFound.description": "Die gesuchte Seite existiert nicht oder wurde verschoben. Keine Sorge – der Beat geht weiter.", "notFound.home": "Zur Startseite",
  "home.nextGig": "Nächster Gig", "home.description": "Belgischer DJ für energiegeladene Festival-Sets, Partyklassiker, Mitsing-Hits und harte Remixes.", "home.nextEvent": "Nächstes Event", "home.tickets": "Tickets & Infos", "home.musicConnects": "Musik, die verbindet", "home.readMore": "Mehr erfahren", "home.bookingsOpen": "Bookings offen", "home.availability": "Verfügbarkeit anfragen", "home.contact": "Kontakt aufnehmen", "home.follow": "Follow the vibe", "home.stats.age": "Alter", "home.stats.experience": "Jahre Erfahrung", "home.stats.shows": "Auftritte", "home.stats.festivals": "Festivals", "home.stats.countries": "Länder",
  "about.title": "Energie, Beats & einzigartige Atmosphäre", "about.subtitle": "Leidenschaft für die Tanzfläche – von Mitsing-Hits und Partyklassikern bis zu harter DnB & Hardstyle.", "about.musicStyle": "Meine Musik & mein Stil", "about.figures": "Zahlen", "about.bookings": "Bookings & Kontakt", "about.interest": "Interesse an einem Booking? Schreib gerne für weitere Informationen und Verfügbarkeit.", "about.drives": "Worauf es ankommt", "about.drivesText": "DJing bedeutet für mich vor allem Atmosphäre und Publikum.", "about.energy": "Energie", "about.energyText": "Ein gutes Set soll Energie geben und die Tanzfläche in Bewegung halten.", "about.music": "Musik", "about.musicText": "Von bekannten Mitsing-Hits bis DnB und harten Remixes. Ich entdecke gerne neue Musik.", "about.audience": "Publikum", "about.audienceText": "Ich lese den Raum und reagiere auf das Geschehen. Das Publikum bestimmt die Richtung mit.",
  "contact.title": "Kontakt & Zusammenarbeit", "contact.heading": "Lass uns zusammenarbeiten", "contact.intro": "Eine Booking-Anfrage, allgemeine Frage, Kollaborationsidee oder Medienanfrage? Fülle das Formular aus und wir melden uns innerhalb von 24 Stunden.", "contact.send": "Nachricht senden", "contact.direct": "Direkter Kontakt", "contact.bookings": "Kontakt & Bookings", "contact.phone": "Telefon", "contact.location": "Ort", "contact.locationValue": "Belgien (europaweit buchbar)", "contact.whatNeed": "Was wir brauchen", "contact.needIntro": "Diese Angaben helfen uns bei einem passenden Angebot:", "contact.date": "Datum & Uhrzeit", "contact.venue": "Ort / Venue", "contact.attendees": "Erwartete Besucherzahl", "contact.vibe": "Musikalische Richtung / Vibe", "contact.budget": "Budgetvorstellung", "contact.socials": "Socials", "contact.faq": "Häufige Fragen", "contact.faqIntro": "Die häufigsten Fragen zu Kontakt und Bookings.",
  "faq.1q": "Wie früh sollte ich buchen?", "faq.1a": "Für Wochenenden und Festivals empfehlen wir 2–3 Monate Vorlauf. Wochentage und kurzfristige Anfragen sind je nach Kalender möglich.",
  "faq.2q": "Was kostet ein Set?", "faq.2a": "Der Preis hängt von Dauer, Ort, Wochentag, Ausstattung und Eventtyp ab. Sende eine Anfrage für ein individuelles Angebot.",
  "faq.3q": "Bringst du eigenes Equipment mit?", "faq.3a": "Normalerweise spiele ich mit dem vorhandenen Equipment (CDJ-3000 / Mixer). Besprich spezielle Anforderungen vorher.",
  "faq.4q": "Spielst du auch auf Hochzeiten oder Firmenevents?", "faq.4a": "Absolut. Ich habe viel Erfahrung mit privaten Events und passe die Musik an die gewünschte Atmosphäre an.",
  "faq.5q": "Wie weit reist du?", "faq.5a": "Von Belgien aus europaweit. Reise- und Übernachtungskosten fallen außerhalb Belgiens zusätzlich an.",
  "faq.6q": "Kann ich eine Demo oder einen Live-Set hören?", "faq.6a": "Klar. Höre Mixe und Produktionen auf SoundCloud oder frage über das Formular eine Live-Demo an.",
  "form.name": "Name", "form.namePlaceholder": "Dein Name", "form.email": "E-Mail", "form.website": "Website", "form.reason": "Worum geht es bei deiner Anfrage?", "form.choose": "Auswählen", "form.phone": "Telefon", "form.eventType": "Eventtyp", "form.eventChoose": "Eventtyp auswählen", "form.questionSubject": "Thema deiner Frage", "form.collaborationType": "Art der Zusammenarbeit", "form.mediaType": "Art der Medienanfrage", "form.date": "Datum", "form.optional": "Optional", "form.location": "Ort", "form.locationPlaceholder": "Stadt / Venue", "form.message": "Nachricht", "form.messagePlaceholder": "Beschreibe kurz dein Event, die Zeit, die erwartete Besucherzahl und was du suchst.", "form.send": "Anfrage senden", "form.sending": "Wird gesendet...", "form.error": "Senden fehlgeschlagen.", "form.retry": "Versuche es erneut oder schreibe direkt an bookings@cannix.be.", "form.successTitle": "Anfrage gesendet", "form.thanks": "Danke für deine Anfrage.", "form.successText": "Wir melden uns so schnell wie möglich.",
  "form.event.club": "Clubabend", "form.event.festival": "Festival", "form.event.party": "Party", "form.event.rave": "Rave", "form.event.private": "Private Party", "form.event.wedding": "Hochzeit", "form.event.other": "Andere", "form.reason.booking": "Ich möchte Cannix buchen", "form.reason.question": "Ich habe eine allgemeine Frage", "form.reason.collaboration": "Ich möchte zusammenarbeiten", "form.reason.media": "Medien oder Interview", "form.question.general": "Allgemeine Informationen", "form.question.music": "Musik und Produktionen", "form.question.availability": "Verfügbarkeit", "form.question.technical": "Technische Frage", "form.question.other": "Andere", "form.collab.artist": "Künstler oder Event", "form.collab.brand": "Marke oder Organisation", "form.collab.music": "Musikalische Zusammenarbeit", "form.collab.other": "Andere", "form.media.interview": "Interview", "form.media.press": "Pressemitteilung", "form.media.photo": "Foto- oder Videoanfrage", "form.media.other": "Andere",
  "gallery.filter": "Nach Jahr filtern", "gallery.list": "Fotogalerie", "gallery.all": "Alle", "gallery.none": "Keine Fotos für {year} gefunden.", "gallery.enlarge": "Vergrößern: {alt}", "gallery.previous": "Vorheriges Foto", "gallery.next": "Nächstes Foto", "gallery.photo": "Foto {current} von {total}", "videos.more": "Mehr Content auf unseren Kanälen", "videos.follow": "Folge uns für neue Uploads, Livestreams und exklusive Behind-the-Scenes-Inhalte.", "videos.youtube": "YouTube-Kanal", "videos.instagram": "Instagram Reels", "videos.close": "Video schließen",
  "legal.privacy": "Datenschutz", "legal.terms": "Bedingungen", "legal.cookies": "Cookies", "legal.contact": "Kontakt", "terms.badge": "Rechtliches", "terms.title": "Allgemeine Geschäftsbedingungen", "terms.version": "Version August 2026", "terms.intro": "Mit der Buchung von DJ Cannix akzeptierst du die folgenden Bedingungen. Bitte lies sie aufmerksam.", "privacy.updated": "Zuletzt aktualisiert: August 2026", "privacy.intro": "Wir respektieren deine Privatsphäre und schützen deine personenbezogenen Daten gemäß DSGVO.", "cookies.title": "Cookie-Richtlinie", "cookies.updated": "Zuletzt aktualisiert: August 2026", "cookies.intro": "Die Website von DJ Cannix verwendet nur unbedingt notwendige funktionale Cookies. Ohne Zustimmung setzen wir keine Tracking-, Marketing- oder Analyse-Cookies.", "cookies.what": "Was sind Cookies?", "cookies.whatText": "Cookies sind kleine Textdateien, die beim Besuch einer Website auf deinem Gerät gespeichert werden. Sie sorgen für die korrekte Funktion und merken sich deine Einstellungen.", "cookies.which": "Welche Cookies verwenden wir?", "cookies.manage": "Cookies verwalten oder löschen", "cookies.manageText": "Du kannst Cookies in den Einstellungen deines Browsers verwalten. Das Deaktivieren funktionaler Cookies kann die Website beeinträchtigen.", "cookies.always": "Immer aktiv", "cookies.inactive": "Nicht aktiv", "cookies.examples": "Beispiele:", "cookies.duration": "Dauer:",
  "cookies.contactText": "Bei Fragen zu unserer Cookie-Richtlinie erreichst du uns unter", "modal.confirm": "Bestätigen", "modal.cancel": "Abbrechen",
  "about.style1": "Als Allround-DJ spiele ich bekannte Partymusik, Mitsing-Hits und harte Remixes. Außerdem spiele und produziere ich Drum & Bass mit Fokus auf Jump Up. Auch Hardstyle und Jumpstyle gehören dazu.", "about.style2": "Ich suche immer neue Musik und Sounds. Was ich spiele, richtet sich nach Publikum, Ort und Atmosphäre – wichtig ist, dass die Menschen in Bewegung bleiben.", "bio.long.1": "Cannix ist ein belgischer DJ und Produzent, der seit über 5 Jahren aktiv ist. Er bewegt sich zwischen verschiedenen Stilen – von Allround-Partys bis zu harten Remixes und energiegeladener Drum & Bass.", "bio.long.2": "Bei Drum & Bass liegt sein Fokus unter anderem auf Jump Up. Auch Hardstyle und Jumpstyle gehören zu seinem Stil. So passt er sich jedem Publikum und Event an.", "bio.long.3": "Neben dem DJing produziert Cannix eigene Musik und experimentiert ständig mit neuen Sounds und Ideen.", "bio.long.4": "Ob hinter den Decks oder im Studio: Das Ziel bleibt, Menschen zu bewegen und eine bleibende Atmosphäre zu schaffen.",
  "terms.s1": "1. Geltungsbereich|Diese Bedingungen gelten für alle Angebote, Vereinbarungen und Bookings mit Cannix. Mit der Bestätigung akzeptiert der Kunde sie vollständig.", "terms.s2": "2. Booking & Bestätigung|Ein Booking ist nach schriftlicher Bestätigung und Eingang eines möglichen Vorschusses verbindlich. Mündliche Absprachen sind nicht bindend.", "terms.s3": "3. Gage & Zahlung|Die Gage steht im Angebot. Bei Bestätigung sind 25 % Vorschuss fällig, der Rest spätestens 7 Tage vor dem Auftritt, sofern nichts anderes vereinbart ist.", "terms.s4": "4. Stornierung durch den Kunden|Mehr als 30 Tage: 25 % der Gage. 14–30 Tage: 50 %. Unter 14 Tage: 100 %. Stornierungen müssen schriftlich erfolgen.", "terms.s5": "5. Stornierung durch den Künstler|Bei höherer Gewalt darf der Künstler stornieren. Der Vorschuss wird vollständig zurückerstattet; ein Ersatz wird nach Möglichkeit empfohlen.", "terms.s6": "6. Technische Anforderungen|Der Kunde stellt die im Rider genannten Anforderungen bereit. Andernfalls darf der Künstler die Gage anpassen oder den Auftritt ablehnen.", "terms.s7": "7. Urheberrecht & Aufnahmen|Kommerzielle Audio- oder Videoaufnahmen benötigen die schriftliche Zustimmung des Künstlers. Werbebilder des Events in sozialen Medien sind erlaubt.", "terms.s8": "8. Haftung|Der Künstler haftet nicht für Schäden durch höhere Gewalt, technische Störungen außerhalb seiner Kontrolle oder Dritte. Die Haftung ist auf die vereinbarte Gage begrenzt.", "terms.s9": "9. Anwendbares Recht|Für alle Vereinbarungen gilt belgisches Recht. Streitigkeiten werden den zuständigen Gerichten am Sitz des Künstlers vorgelegt.",
  "privacy.s1": "1. Wer sind wir?|Cannix ist ein Musikunternehmen und DJ/Entertainer in Belgien. Wir verarbeiten personenbezogene Daten für Booking-Anfragen und Kommunikation.", "privacy.s2": "2. Welche Daten sammeln wir?|Das Formular erfasst Name, E-Mail, Telefon, Eventtyp, Datum, Ort und Nachricht – ausschließlich zur Bearbeitung der Anfrage.", "privacy.s3": "3. Zweck der Verarbeitung|Die Daten dienen der Beantwortung von Anfragen, Angeboten sowie Verträgen und Rechnungen. Keine kommerziellen E-Mails ohne Zustimmung.", "privacy.s4": "4. Wie lange speichern wir Daten?|So lange wie nötig: Formulardaten maximal 2 Jahre, Booking- und Rechnungsdaten 7 Jahre gemäß belgischem Recht.", "privacy.s5": "5. Weitergabe an Dritte|Keine Weitergabe außer zur Vertragserfüllung oder wenn gesetzlich vorgeschrieben. Keine Tracking-Cookies oder Werbenetzwerke.", "privacy.s6": "6. Deine Rechte|Du kannst Auskunft, Berichtigung, Löschung und Übertragbarkeit verlangen sowie der Verarbeitung widersprechen. Kontakt: bookings@cannix.be.", "privacy.s7": "7. Kontakt & Beschwerden|Fragen an bookings@cannix.be. Beschwerden können bei der belgischen Datenschutzbehörde eingereicht werden.",
  "cookies.functional": "Funktionale Cookies|Für die Website notwendig und nicht deaktivierbar.|Sitzungs-ID, Sprache, Navigationsstatus|Sitzung / max. 1 Jahr", "cookies.analytics": "Analyse-Cookies|Wir verwenden derzeit keine externen Analysedienste.|Keine externen Tracker|Nicht zutreffend", "cookies.marketing": "Marketing-Cookies|Wir setzen keine Marketing- oder Werbe-Cookies.|Keine Werbe-Cookies|Nicht zutreffend",
  "bio.short": "Cannix ist DJ und Produzent mit über 5 Jahren Erfahrung. Er bewegt sich zwischen Partymusik, Mitsing-Hits, harten Remixes und Drum & Bass, ergänzt durch Jump Up, Hardstyle und Jumpstyle.\n\nDas Ziel ist einfach: Menschen bewegen, ihre Aufmerksamkeit halten und Energie schaffen.", "video.1.title": "Mexican Wave Party 2026 - Highlights", "video.1.description": "Ein energiegeladenes Set beim Mexican Wave Party 2026 mit voller Tanzfläche.", "video.2.title": "Silent Disco 2025 - Full Set", "video.2.description": "Ein einzigartiges Silent-Disco-Erlebnis, bei dem jeder auf seiner Frequenz tanzt.", "video.3.title": "PEMP 2024 - DJ Cannix Live", "video.3.description": "Live-Aufnahme vom PEMP-Festival 2024.", "video.4.title": "Blacklight Party 2024", "video.4.description": "Neon-Vibes und Blacklight-Energie mit DJ Cannix.", "video.5.title": "Mexican Wave Party 2024", "video.5.description": "Eine der größten Mexican-Wave-Ausgaben überhaupt.", "video.6.title": "'t Leerke 2025 - Aftermovie", "video.6.description": "Aftermovie eines unvergesslichen Abends im 't Leerke.",
  "validation.name": "Gib deinen Namen ein.", "validation.nameLong": "Der Name ist zu lang.", "validation.email": "Gib eine gültige E-Mail-Adresse ein.", "validation.phone": "Gib deine Telefonnummer ein.", "validation.phoneLong": "Die Telefonnummer ist zu lang.", "validation.reason": "Wähle den Anfragegrund.", "validation.eventType": "Wähle einen Eventtyp.", "validation.questionType": "Wähle das Thema deiner Frage.", "validation.collaborationType": "Wähle die Art der Zusammenarbeit.", "validation.mediaType": "Wähle die Art der Medienanfrage.", "validation.location": "Gib den Ort ein.", "validation.locationLong": "Der Ort ist zu lang.", "validation.message": "Beschreibe kurz deine Anfrage (mind. 20 Zeichen).", "validation.messageLong": "Die Nachricht ist zu lang.",
};

const dictionaries: Record<Language, Dictionary> = { nl, en, fr, de };

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey | string, variables?: Record<string, string | number>) => string;
  languageInfo: (typeof languages)[number];
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({
  children,
  initialLanguage,
}: {
  children: ReactNode;
  initialLanguage?: Language;
}) {
  const [language, setLanguageState] = useState<Language>(initialLanguage || "nl");

  useEffect(() => {
    if (initialLanguage) {
      setLanguageState(initialLanguage);
      return;
    }
    const saved = window.localStorage.getItem("cannix-language") as Language | null;
    if (saved && languages.some((item) => item.value === saved)) setLanguageState(saved);
  }, [initialLanguage]);

  useEffect(() => {
    const info = languages.find((item) => item.value === language) || languages[0];
    document.documentElement.lang = info.htmlLang;
    window.localStorage.setItem("cannix-language", language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: (next) => setLanguageState(next),
    languageInfo: languages.find((item) => item.value === language) || languages[0],
    t: (key, variables) => {
      let text = (dictionaries[language] as Record<string, string>)[key] || (nl as Record<string, string>)[key] || key;
      Object.entries(variables || {}).forEach(([name, replacement]) => {
        text = text.replaceAll(`{${name}}`, String(replacement));
      });
      return text;
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}

export const getTranslatedPair = (value: string, language: Language) => {
  const [title, description] = value.split("|");
  return { title: title || "", description: description || "" };
};
